#!/usr/bin/env php
<?php

use Dew\Cli\Commands\CliCommand;
use Dew\Cli\Commands\DatabaseCreateCommand;
use Dew\Cli\Commands\DatabaseDeleteCommand;
use Dew\Cli\Commands\DeployCommand;
use Dew\Cli\Commands\EnvironmentCreateCommand;
use Dew\Cli\Commands\EnvironmentDestroyCommand;
use Dew\Cli\Commands\InitCommand;
use Dew\Cli\Commands\LoginCommand;
use Dew\Cli\Commands\ProjectConnectCommand;
use Dew\Cli\Commands\ProjectCreateCommand;
use Dew\Cli\Commands\RollbackCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require_once __DIR__.'/vendor/autoload.php';
} else {
    require_once __DIR__.'/../../autoload.php';
}

$app = new Application('Dew CLI', 'v0.0.1');

$app->add(new LoginCommand);
$app->add(new ProjectCreateCommand);
$app->add(new ProjectConnectCommand);
$app->add(new InitCommand);
$app->add(new EnvironmentCreateCommand);
$app->add(new EnvironmentDestroyCommand);
$app->add(new DatabaseCreateCommand);
$app->add(new DatabaseDeleteCommand);
// $app->add(new CliCommand);
$app->add(new DeployCommand);
$app->add(new RollbackCommand);

$app->run();
